name: Release

on:
  push:
    tags:
      - 'v.*' # Trigger the workflow on tags matching v.*

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grants permission to upload assets to the release

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Download the artifact from the `build.yml` workflow
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ steps.artifact.outputs.filename }} # Use the dynamic artifact name from build.yml

      # Step 3: Create a GitHub release
      - name: Create GitHub Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }} # The tag that triggered the workflow
          release_name: Release ${{ github.ref_name }}
          body: |
            This release was automatically generated.
          draft: false
          prerelease: false

      # Step 4: Upload the artifact to the release
      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./build/distributions/content/*/* # Correct path from build.yml
          asset_name: ${{ steps.artifact.outputs.filename }} # Use the dynamic artifact name
          asset_content_type: application/zip # Replace with the correct MIME type if needed